import Navbar from '@/components/common-components/Navbar';
import { Space_Mono, Lexend_Deca, } from "next/font/google";
import Footer from '@/components/common-components/Footer';
import './globals.css';
import MainContext from '@/components/MainContext';

const spaceMono = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-mono',
});

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-sans',
});


export const metadata = {
  title: "scoot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceMono.variable} ${lexendDeca.variable}  antialiased`}>
        <MainContext>
          <Navbar/>
          {children}
          <Footer/>
        </MainContext>
      </body>
    </html>
  );
}
